[workspace]
authors = ["Nacef Guessaymi <nacefguess@hotmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "bioinfo"
platforms = ["osx-arm64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
numpy = "*"
scipy = "*"
matplotlib = "*"
seaborn = "*"
jupyterlab = "*"
scikit-learn = "*"
perl = "*"
pandas = ">=2.3.3,<3"
biopython = "*"
prody = ">=2.4.1,<3"
trimmomatic = ">=0.40,<0.41"
hisat2 = ">=2.2.1,<3"
samtools = ">=1.22.1,<2"
subread = ">=2.1.1,<3"
polars = ">=1.35.1,<2"

[pypi-dependencies]
multiqc = ">=1.32, <2"
